version: "3.7"
services:
  api:
    build:
      cache_from: josiahwolfoberholtzer/on-exactitude-in-science-api:latest
      context: api
    command: gunicorn --conf gunicorn.conf.py maps.app:app
    environment:
      GUNICORN_ACCESSLOG: "-"
      GUNICORN_BIND: 0.0.0.0:9090
      GUNICORN_CAPTURE_OUTPUT: "true"
      GUNICORN_ERRORLOG: "-"
      GUNICORN_LOGLEVEL: debug
      GUNICORN_RELOAD: "true"
      GUNICORN_WORKERS: 4
      GUNICORN_WORKER_CLASS: aiohttp.worker.GunicornUVLoopWebWorker
      GUNICORN_ENABLE_STDIO_INHERITANCE: "true"
    depends_on:
    - janusgraph-healthcheck
    - memcached
    ports:
    - 9090:9090
    volumes:
    - ./api:/app
    - ./data:/data
  gui:
    build:
      context: gui
    ports:
    - 8080:80
    volumes:
    - ./gui/dist:/var/www/html
  cassandra:
    image: cassandra:3.11.6
    ports:
    - 9042:9042
    - 9160:9160
  scylla:
    image: scylladb/scylla:4.1.6
  elasticsearch:
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      http.host: 0.0.0.0
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      cluster.name: docker-cluster
      xpack.security.enabled: "false"
      discovery.zen.minimum_master_nodes: 1
    #image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    image: elasticsearch:7.6.2
    ports:
    - 9200:9200
  janusgraph:
    depends_on:
    - scylla
    - elasticsearch
    image: janusgraph/janusgraph:0.5.2
    ports:
    - 8182:8182
    volumes:
    - ./janusgraph:/etc/opt/janusgraph:ro
  janusgraph-healthcheck:
    command: "-sSf --retry 60 --retry-delay 5 --retry-max-time 180 --retry-connrefused 'http://janusgraph:8182?gremlin=100-1'"
    depends_on:
    - janusgraph
    image: curlimages/curl:latest
  memcached:
    image: memcached:latest
    ports:
    - 11211:11211
