version: "3.7"
services:
  api:
    build:
      context: api
    command: gunicorn --conf gunicorn.conf.py maps.app:app
    environment:
      GUNICORN_ACCESSLOG: "-"
      GUNICORN_BIND: 0.0.0.0:9090
      GUNICORN_CAPTURE_OUTPUT: "true"
      GUNICORN_ERRORLOG: "-"
      GUNICORN_LOGLEVEL: debug
      GUNICORN_RELOAD: "true"
      GUNICORN_WORKERS: 4
      GUNICORN_WORKER_CLASS: aiohttp.worker.GunicornUVLoopWebWorker
    depends_on:
    - janusgraph-healthcheck
    ports:
    - 9090:9090
    volumes:
    - ./api:/app
    - ./data:/data
  gui:
    build:
      context: gui
    ports:
    - 8080:8080
    volumes:
    - ./gui:/app
  cassandra:
    image: cassandra:3.11.6
    ports:
    - 9042:9042
    - 9160:9160
  elasticsearch:
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      http.host: 0.0.0.0
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      cluster.name: docker-cluster
      xpack.security.enabled: "false"
      discovery.zen.minimum_master_nodes: 1
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
    - 9200:9200
  janusgraph:
    depends_on:
    - cassandra
    - elasticsearch
    environment:
      JANUS_PROPS_TEMPLATE: cql-es
      gremlinserver.channelizer: org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer
      janusgraph.index.search.hostname: elasticsearch
      janusgraph.schema.default: "none"
      janusgraph.storage.batch-loading: "true"
      janusgraph.storage.hostname: cassandra
      janusgraph.storage.port: 9042
    image: janusgraph/janusgraph:0.5
    ports:
    - 8182:8182
  janusgraph-healthcheck:
    command: "-sSf --retry 60 --retry-delay 5 --retry-connrefused 'http://janusgraph:8182?gremlin=100-1'"
    depends_on:
    - janusgraph
    image: curlimages/curl:latest
  janusgraph-test:
    image: janusgraph/janusgraph:0.5
    environment:
      gremlinserver.channelizer: org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer
