version: "3.7"
services:
  api:
    build:
      context: api
    ports:
    - 9090:9090
    volumes:
    - ./api:/app
    - ./data:/data
  gui:
    build:
      context: gui
    ports:
    - 8080:8080
    volumes:
    - ./gui:/app
  cassandra:
    image: cassandra:3.11.6
    ports:
    - 9042:9042
    - 9160:9160
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      http.host: 0.0.0.0
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      cluster.name: docker-cluster
      xpack.security.enabled: "false"
      discovery.zen.minimum_master_nodes: 1
    ports:
    - 9200:9200
  janusgraph:
    depends_on:
    - cassandra
    - elasticsearch
    image: janusgraph/janusgraph:0.5
    environment:
      JANUS_PROPS_TEMPLATE: cql-es
      janusgraph.index.search.hostname: elasticsearch
      janusgraph.storage.hostname: cassandra
      janusgraph.storage.port: 9042
    ports:
    - 8182:8182
  janusgraph-test:
    image: janusgraph/janusgraph:0.5
