const data = {
  result: {
    edges: [
      {
        id: '4qw-6dc-i6t-6gw',
        label: 'alias_of',
        source: 8256,
        target: 8384,
      },
      {
        id: '8p4-6dc-i6t-cr4',
        label: 'alias_of',
        source: 8256,
        target: 16528,
      },
      {
        id: '554-6dc-i6t-crs',
        label: 'alias_of',
        source: 8256,
        target: 16552,
      },
      {
        id: 'ao8-6dc-i6t-j2w',
        label: 'alias_of',
        source: 8256,
        target: 24728,
      },
      {
        id: '7ig-6dc-i6t-vm8',
        label: 'alias_of',
        source: 8256,
        target: 40976,
      },
      {
        id: '7wo-6dc-i6t-ys0',
        label: 'alias_of',
        source: 8256,
        target: 45072,
      },
      {
        id: '9hk-6dc-i6t-11xs',
        label: 'alias_of',
        source: 8256,
        target: 49168,
      },
      {
        id: 'c1g5k-6dc-iz9-gn060',
        label: 'credited_with',
        role: 'Remix',
        source: 8256,
        target: 27947160,
      },
      {
        id: 'ps6bs-6dc-iz9-tjljs',
        label: 'credited_with',
        role: 'Remix',
        source: 8256,
        target: 49623256,
      },
      {
        id: 'brea0-6dc-lcl-gvyl4',
        label: 'released',
        source: 8256,
        target: 28365016,
      },
      {
        id: 'bxvd4-6dc-lcl-h23tk',
        label: 'released',
        source: 8256,
        target: 28651736,
      },
      {
        id: 'copoo-6dc-lcl-h61zs',
        label: 'released',
        source: 8256,
        target: 28835992,
      },
      {
        id: 'cotmw-6dc-lcl-hp0pk',
        label: 'released',
        source: 8256,
        target: 29720792,
      },
      {
        id: 'etts8-6dc-lcl-jjtug',
        label: 'released',
        source: 8256,
        target: 32837848,
      },
      {
        id: 'eu8eg-6dc-lcl-jk6hk',
        label: 'released',
        source: 8256,
        target: 32854232,
      },
      {
        id: 'eu1oo-6dc-lcl-jny9s',
        label: 'released',
        source: 8256,
        target: 33030208,
      },
      {
        id: 'n8pvs-6dc-lcl-raatc',
        label: 'released',
        source: 8256,
        target: 45830208,
      },
      {
        id: 'psw08-6dc-lcl-thhn4',
        label: 'released',
        source: 8256,
        target: 49524880,
      },
      {
        id: 'bzrbc-6dc-lcl-xi9c0',
        label: 'released',
        source: 8256,
        target: 56279232,
      },
      {
        id: 'bs3k8-6dc-lcl-1dzac0',
        label: 'released',
        source: 8256,
        target: 83947536,
      },
      {
        id: 'coq2w-6dc-lcl-1gl4wg',
        label: 'released',
        source: 8256,
        target: 88326160,
      },
      {
        id: 'coyrs-6dc-lcl-1gm0i8',
        label: 'released',
        source: 8256,
        target: 88367120,
      },
      {
        id: 'psr9k-6dc-lcl-1mrc8w',
        label: 'released',
        source: 8256,
        target: 98693312,
      },
      {
        id: 'psf0o-6dc-lcl-2h998w',
        label: 'released',
        source: 8256,
        target: 149917712,
      },
    ],
    vertices: [
      {
        id: 8256,
        label: 'artist',
        eid: 1,
        name: 'The Persuader',
      },
      {
        id: 8384,
        label: 'artist',
        eid: 239,
        name: 'Jesper Dahlbäck',
      },
      {
        id: 16528,
        label: 'artist',
        eid: 196957,
        name: "Janne Me' Amazonen",
      },
      {
        id: 16552,
        label: 'artist',
        eid: 16055,
        name: 'Groove Machine',
      },
      {
        id: 24728,
        label: 'artist',
        eid: 439150,
        name: 'The Pinguin Man',
      },
      {
        id: 40976,
        label: 'artist',
        eid: 19541,
        name: 'Dick Track',
      },
      {
        id: 45072,
        label: 'artist',
        eid: 25227,
        name: 'Lenk',
      },
      {
        id: 49168,
        label: 'artist',
        eid: 278760,
        name: 'Faxid',
      },
      {
        id: 27947160,
        label: 'track',
        eid: '119-B1',
        name: 'The Big Bang Theory (Remix By Stephan G & The Persuader)',
        position: 'B1',
      },
      {
        id: 28365016,
        label: 'release',
        eid: 1,
        country: 'Sweden',
        formats: [
          '33 ⅓ RPM',
          '12"',
          'Vinyl',
        ],
        genres: [
          'Electronic',
        ],
        is_main_release: true,
        name: 'Stockholm',
        styles: [
          'Deep House',
        ],
        year: 1999,
      },
      {
        id: 28651736,
        label: 'release',
        eid: 79,
        country: 'Sweden',
        formats: [
          '12"',
          'Vinyl',
        ],
        genres: [
          'Electronic',
        ],
        is_main_release: true,
        name: 'City Of Islands',
        styles: [
          'Deep House',
          'Tech House',
        ],
        year: 1998,
      },
      {
        id: 28835992,
        label: 'track',
        eid: '399-A1',
        name: 'Funk Seven',
        position: 'A1',
      },
      {
        id: 29720792,
        label: 'track',
        eid: '399-B',
        name: 'Tandori Funk',
        position: 'B',
      },
      {
        id: 32837848,
        label: 'track',
        eid: '1220-8',
        name: 'Slussen (Go Dub Mix By Erot)',
        position: '8',
      },
      {
        id: 32854232,
        label: 'track',
        eid: '1222-9',
        name: 'From West To South',
        position: '9',
      },
      {
        id: 33030208,
        label: 'track',
        eid: '1220-9',
        name: 'Djurgardsbron',
        position: '9',
      },
      {
        id: 45830208,
        label: 'release',
        eid: 4664,
        country: 'Sweden',
        formats: [
          '33 ⅓ RPM',
          '12"',
          'EP',
          'Vinyl',
        ],
        genres: [
          'Electronic',
        ],
        is_main_release: true,
        name: 'Stockholm By Night',
        styles: [
          'Deep House',
          'House',
        ],
        year: 1997,
      },
      {
        id: 49524880,
        label: 'track',
        eid: '5955-9',
        name: 'Playing Your Game',
        position: '9',
      },
      {
        id: 49623256,
        label: 'track',
        eid: '5955-1',
        name: 'Discophrenia (The Persuader Remix)',
        position: '1',
      },
      {
        id: 56279232,
        label: 'release',
        eid: 101,
        country: 'Sweden',
        formats: [
          '33 ⅓ RPM',
          '12"',
          'Vinyl',
        ],
        genres: [
          'Electronic',
        ],
        is_main_release: true,
        name: 'Morgon Sol',
        styles: [
          'Deep House',
          'Tech House',
        ],
        year: 1998,
      },
      {
        id: 83947536,
        label: 'track',
        eid: '3-4',
        name: "What's The Time, Mr. Templar",
        position: '4',
      },
      {
        id: 88326160,
        label: 'release',
        eid: 400,
        country: 'Sweden',
        formats: [
          '33 ⅓ RPM',
          '12"',
          'Vinyl',
        ],
        genres: [
          'Electronic',
        ],
        is_main_release: false,
        name: 'A View From Slussen',
        styles: [
          'Deep House',
        ],
        year: 1998,
      },
      {
        id: 88367120,
        label: 'release',
        eid: 401,
        country: 'Sweden',
        formats: [
          '12"',
          'Vinyl',
        ],
        genres: [
          'Electronic',
        ],
        is_main_release: true,
        name: 'Pleasure',
        styles: [
          'Deep House',
        ],
        year: 1998,
      },
      {
        id: 98693312,
        label: 'track',
        eid: '5955-7',
        name: 'From West To South',
        position: '7',
      },
      {
        id: 149917712,
        label: 'track',
        eid: '5955-3',
        name: 'Naked Woman',
        position: '3',
      },
    ],
  },
};

export { data };
