env:
  browser: true
  es2020: true
  mocha: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  import/no-named-default: 0
  import/prefer-default-export: 0
  no-console:
  - 0
  no-param-reassign:
  - error
  - props: false
  no-plusplus:
  - error
  - allowForLoopAfterthoughts: true
  no-use-before-define:
  - error
  - functions: false
  one-var:
  - warn
  - var: always
    let: always
    const: consecutive
  sort-imports:
  - error
