env:
  browser: true
  es2020: true
  mocha: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  one-var:
  - 2
  - var: always
    let: always
    const: always
