env:
  browser: true
  es2020: true
  mocha: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  one-var:
  - error
  - var: always
    let: always
    const: always
  import/no-named-default: 0
  import/prefer-default-export: 0
  no-param-reassign:
  - error
  - props: false
