apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: on-exactitude-in-science
resources:
- api-deployment.yml
- api-ingress.yml
- api-service.yml
- gui-deployment.yml
- gui-ingress.yml
- gui-service.yml
- elasticsearch-service.yml
- elasticsearch-statefulset.yml
- janusgraph-deployment.yml
- janusgraph-service.yml
- namespace.yml
- scylla-configmap.yml
- scylla-service.yml
- scylla-statefulset.yml
images:
- name: josiahwolfoberholtzer/on-exactitude-in-science-api
  newName: josiahwolfoberholtzeron-exactitude-in-science-api
  newTag: latest
- name: josiahwolfoberholtzer/on-exactitude-in-science-gui
  newName: josiahwolfoberholtzeron-exactitude-in-science-gui
  newTag: latest
