apiVersion: batch/v1
kind: Job
metadata:
  name: loader
spec:
  template:
    spec:
      containers:
      - name: loader
        image: josiahwolfoberholtzer/on-exactitude-in-science-api:latest
        command:
        - /load.sh
        volumeMounts:
        - mountPath: /load.sh
          name: loader-data
          subPath: load.sh
      restartPolicy: Never
      volumes:
      - name: loader-data
        configMap:
          defaultMode: 0777
          name: loader
  backoffLimit: 0
