apiVersion: batch/v1
kind: Job
metadata:
  name: schema-loader
spec:
  template:
    spec:
      containers:
      - name: schema-loader
        image: josiahwolfoberholtzer/on-exactitude-in-science-api:latest
        command:
        - python3
        - -m
        - maps
        - schema
        - load
      restartPolicy: Never
  backoffLimit: 0
