name: Deployment
on:
  push:
    branches:
    - master
env:
  API_IMAGE: josiahwolfoberholtzer/on-exactitude-in-science-api
  GUI_IMAGE: josiahwolfoberholtzer/on-exactitude-in-science-gui
jobs:
  images:
    name: Update Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: API image
      uses: docker/build-push-action@v1
      with:
        username: josiahwolfoberholtzer
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: josiahwolfoberholtzer/on-exactitude-in-science-api
        tags: latest
        tag_with_sha: true
        path: api
    - name: GUI image
      uses: docker/build-push-action@v1
      with:
        username: josiahwolfoberholtzer
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: josiahwolfoberholtzer/on-exactitude-in-science-gui
        tags: latest
        tag_with_sha: true
        path: gui
  kubernetes:
    name: Update Kubernetes
    needs:
    - images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set IMAGE_TAG
      run: echo "::set-env name=IMAGE_TAG::sha-$(git rev-parse --short ${{ github.sha }})"
    - name: Set up kubectl
      uses: matootie/dokube@v1.3.2
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: on-exactitude-in-science
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.8.1"
    - name: Set image tags
      working-directory: ./kubernetes
      run: |
        kustomize edit set image ${API_IMAGE}=${API_IMAGE}:${IMAGE_TAG}
        kustomize edit set image ${GUI_IMAGE}=${GUI_IMAGE}:${IMAGE_TAG}
    - name: Debug
      run: kustomize build ./kubernetes
    - name: Apply
      run: kustomize build ./kubernetes | kubectl apply -f -
