name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  api:
    name: API tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build API container
      run: docker-compose build api
    - name: Pull Docker images
      run: docker-compose pull
    - name: Bring containers online
      run: docker-compose up -d scylla-a scylla-b scylla-c elasticsearch janusgraph
    - name: Wait for JanusGraph
      run: docker-compose run --rm janusgraph-healthcheck
    - name: Load schema
      run: docker-compose run --rm api python3 -m maps schema --graph testgraph load
    - name: Run API tests
      run: docker-compose run --rm api make test
  gui:
    name: GUI tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build GUI container
      run : docker-compose build gui
  push:
    name: Push Docker images
    runs-on: ubuntu-latest
    needs:
    - api
    - gui
    steps:
    - uses: actions/checkout@v2
    - name: Push API image
      run: make -C api push
    - name: Push GUI image
      run: make -C gui push
