name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build API container
      run: docker-compose build api
    - name: Build GUI container
      run : docker-compose build gui
    - name: Pull Docker images
      run: docker-compose pull
