name: Testing
on:
  pull_request:
    branches:
    - master
jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull Docker images
      run: |
        docker-compose pull
        docker pull josiahwolfoberholtzer/on-exactitude-in-science-api:latest
    - name: Build API container
      run: docker-compose build api
    - name: Bring containers online
      run: docker-compose up -d scylla-a scylla-b scylla-c elasticsearch janusgraph
    - name: Wait for JanusGraph
      run: docker-compose run --rm janusgraph-healthcheck
    - name: Load schema
      run: docker-compose run --rm api python3 -m maps schema --graph testgraph load
    - name: Run API tests
      run: docker-compose run --rm api make test
    - name: Dump Docker logs
      if: ${{ failure() }}
      run: docker-compose logs
  gui:
    name: GUI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gui
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
